# Generated by Django 2.2.10 on 2021-09-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_details',
            name='image1',
            field=models.ImageField(upload_to='media'),
        ),
    ]
