# Generated by Django 2.2.10 on 2021-09-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210922_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_details',
            name='image1',
            field=models.ImageField(upload_to='images'),
        ),
    ]
