# Generated by Django 2.2.10 on 2021-09-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210922_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_details',
            name='image1',
            field=models.ImageField(upload_to='images'),
        ),
    ]
